name: ape-recursion-error

plugins:
  - name: foundry
    version: "0.6.14"
  - name: etherscan

default_ecosystem: ethereum

ethereum:
  sepolia_fork:
    default_provider: foundry
    gas_limit: "auto"

contracts_folder: src/contracts
